Prod 2219 refactor learn folder structure
topcoder-platform/micro-frontends-self-service-app pull request #481
Opened 2022-06-17 22:07 UTC by vas3a

https://topcoder.atlassian.net/browse/PROD-2219

Update folder structure for the learn tool

2022-06-17 22:27 UTC, brooketopcoder requested changes
just one tiny change...

2022-06-17 22:27 UTC, brooketopcoder commented on src-ts/tools/learn/course-details/course-curriculum/CourseCurriculum.tsx
> +import { TcAcademyPolicyModal } from '../tc-academy-policy-modal'
i see now that this modal is only in the course-curriculum, so let's nest its folder

/course-curriculum/tc-academy-policy-modal

2022-06-17 22:29 UTC, brooketopcoder commented on src-ts/tools/learn/course-details/course-curriculum/CourseCurriculum.tsx
> +import { TcAcademyPolicyModal } from '../tc-academy-policy-modal'
i wend ahead and changed this myself

2022-06-17 22:30 UTC, brooketopcoder approved these changes

2022-06-20 15:41 UTC, testflyjets approved these changes

2022-06-20 16:01 UTC, merged